spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899741832214-1hmu97ddimt008ojq5rbjnipqvejijue.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moodmate?&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
#      show_sql: true
