spring:
  config:
    import: "classpath:env-local.properties"   # 기본값: 로컬용 불러오기
    #import: "classpath:env-prod.properties"   # 배포 시 이걸로 교체

  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show-sql: true

springdoc:
  override-with-generic-response: false
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: true
  api-docs:
    resolve-schema-properties: false

## Google Gemini API 설정 (새로 추가)
gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: "gemini-2.5-flash"        # gemini-1.5-flash 사용 불가 -> gemini-2.5-flash로 대체
    timeout: 30


# 로깅 설정
logging:
  level:
    com.moodmate.domain.feedback.service.GeminiService: DEBUG
    # com.moodmate.domain.feedback.service.OpenAiService: INFO

# application.properties 설정 (대안)
# openai.api.key=${OPENAI_API_KEY:your-openai-api-key-here}
# openai.api.model=gpt-3.5-turbo
# openai.api.url=https://api.openai.com/v1/chat/completions
# openai.api.timeout=30

jwt:
  issuer: moodmate@gmail.com
  secret_key: ${JWT_SECRET_KEY}

