spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 899741832214-1hmu97ddimt008ojq5rbjnipqvejijue.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

          kakao:
            client-id: e131931e1bafa95325fcdb4602ec35ae
            client-secret: 4pswbvGVTYymk56Z1PWGy56EqIEcuvKe
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moodmate?&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
#      show_sql: true
